# Generated by Django 3.1.1 on 2020-09-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
