# Generated by Django 3.1.1 on 2020-09-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_form',
            new_name='ContactForm',
        ),
    ]
